name: pyhpc-bench-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - numpy
  - pytorch
  - tensorflow>=2.0
  - theano
  - numba
  - click
  - scipy
  - pip:
    - bohrium
    - jaxlib
    - jax
